name: Continuous Integration - Test

on:
  push:
    branches: ["main"]  # триггер на изменения ветки main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Версия интерпретатора Python

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
        
      - name: Check if tests passed
        if: failure()
        run: exit 1  # Если тесты провалились, остановить дальнейшие шаги
