name: Continuous Integration

on:
  push:
    branches: ["main"]      # Триггер на коммиты в основную ветку
    tags:                   # Реагирование на создание тегов
      - '*'                 # Любой тег
  pull_request:             # Реагирование на открытие pull request'ов

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/test_prod.py
